version: '3'

services:
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    network_mode: host # 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      SLAVE_SYNC_USER: "sync_admin" # 用于同步的账号，由master创建
      SLAVE_SYNC_PASSWORD: "123456"
      ADMIN_USER: "root"
      ADMIN_PASSWORD: "123456"
      MASTER_HOST: <mysql-master-host> # master地址，开启主从同步需要连接master
      TZ: "Asia/Shanghai" # 设置时区
    volumes: 
      - ./script/slave.sh:/docker-entrypoint-initdb.d/slave.sh
      - /home/mysql/data:/var/lib/mysql
    command:
      - "--server-id=2"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      - "--lower-case-table-names=1"
