version: '3'

services:
  redis-slave:
    image: redis:5.0-alpine
    command: redis-server --slaveof <redis_master_host> 6379
    network_mode: host
      
  redis-sentinel:
    image: bitnami/redis-sentinel:5.0
    network_mode: host
    environment:
      - REDIS_MASTER_HOST=<redis_master_host>
      - REDIS_MASTER_PORT=6379
    depends_on:
      - redis-slave
